# delelopment
system:
  # 设定模式(debug/release/test，正式版改为release)
  mode: debug
  # 程序监听端口
  port: :8888
  # rsa公钥文件路径
  rsa-public-key: ./config/public_key.pem
  # rsa私钥文件路径
  rsa-private-key: ./config/private_key.pem
  # I18国际化指定语言，默认支持en和zh
  i18n-language: zh

logs:
  # 日志等级(-1:Debug，0:Info，1:Warn，2:Error，3:DPanic，4:Panic，5:Fatal，-1<=level<=5，参照zap.level源码)
  level: -1
  # 日志路径
  path: logs
  # 文件最大大小，M
  max-size: 50
  # 备份数
  max-backups: 10
  # 存放时间，天
  max-age: 30
  # 是否压缩
  compress: false

mysql:
  # 用户名
  username: root
  # 密码
  passowrd: ''
  # 数据库名
  database: news_app
  # 主机地址
  host: 127.0.0.1
  # 端口
  port: 3306
  # 连接字符串参数
  query: parseTime=True&loc=Local&timeout=10000ms
  # 是否打印日志
  log-mode: true
  # 编码方式
  charset: utf8mb4
  # 字符集(utf8mb4_general_ci速度比utf8mb4_unicode_ci快些)
  collation: utf8mb4_general_ci
  # 是否初始化数据(没有初始数据时使用，已发布正式版改为false)
  init-data: true

redis:
  # 密码 
  password: ''
  # 数据库名
  database: 0
  # 主机地址端口 
  addr: 127.0.0.1:6379

# casbin配置
casbin:
  # 模型配置文件
  model-path: './config/rbac.conf'

# jwt配置
jwt:
  # 签发人
  issuer: 'cc-news'
  # 主题
  subject: 'usertoken'
  # token过期时间，小时
  timeout: 24
  # 黑名单宽限时间，秒
  blacktime :  10
  # 刷新token最大过期时间, 小时
  max-refresh: 12000
  
# 令牌桶限流配置
ratelimit:
  # 填充一个令牌需要的时间间隔，毫秒
  fill-interval: 2
  # 桶容量
  capacity: 1000

snowflake:
  # 同一时间戳内生成 ID 的不同节点或进程，中间位
  workerID: 1
  # 在不同的数据中心或区域生成的 ID 是唯一的，最低位
  datacenterID: 1